import type { Coin, GameState, GridType, Monster, MonsterType, Player } from "./types";

export const PACMAN_SIZE = 48;
export const MONSTER_SIZE = 48;
export const CELL_SIZE = 64;
export const COIN_SIZE = 8;
export const SCORE_WEIGHT = 10;
export const MONSTER_COLOR: Record<MonsterType, string> = {
  red: "#FF3B30",
  pink: "#FF8ED6",
  cyan: "#2EEBFF",
  orange: "#FFA938",
  green: "#80FF5A",
};

export const INITIAL_PLAYER: Player = { position: { row: 5, column: 10 }, direction: "right" };
export const INITIAL_MONSTERS: Monster[] = [
  { position: { row: 1, column: 1 }, type: "red" },
  { position: { row: 1, column: 19 }, type: "pink" },
  { position: { row: 9, column: 19 }, type: "orange" },
  { position: { row: 9, column: 1 }, type: "green" },
];

export const INITIAL_GRID: GridType = [
  [
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
  ],
  [
    "blocked",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "blocked",
  ],
  [
    "blocked",
    "open",
    "blocked",
    "open",
    "blocked",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "blocked",
    "open",
    "blocked",
    "open",
    "blocked",
  ],
  [
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "open",
    "open",
    "blocked",
  ],
  [
    "blocked",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "blocked",
  ],
  [
    "blocked",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "blocked",
  ],
  [
    "blocked",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "blocked",
  ],
  [
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "open",
    "open",
    "blocked",
  ],
  [
    "blocked",
    "open",
    "blocked",
    "open",
    "blocked",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "blocked",
    "open",
    "blocked",
    "open",
    "blocked",
  ],
  [
    "blocked",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "blocked",
    "blocked",
    "open",
    "open",
    "open",
    "open",
    "blocked",
    "open",
    "open",
    "open",
    "blocked",
  ],
  [
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
    "blocked",
  ],
];

export const initializeCoins = (grid: GridType, player: Player) => {
  const rows = grid.length;
  const columns = grid[0].length;
  const initialPlayerPosition = player.position;
  const coins: Coin[] = [];
  for (let row = 0; row < rows; row++) {
    for (let column = 0; column < columns; column++) {
      if (
        (initialPlayerPosition.row !== row || initialPlayerPosition.column !== column) &&
        grid[row][column] === "open"
      ) {
        coins.push({ position: { row: row, column: column } });
      }
    }
  }
  return coins;
};

export const INITIAL_GAME_STATE: GameState = {
  player: INITIAL_PLAYER,
  monsters: INITIAL_MONSTERS,
  coins: initializeCoins(INITIAL_GRID, INITIAL_PLAYER),
  score: 0,
  isGameOver: false,
  hasWon: false,
  hasGameStarted: false,
};
